---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: image-scanner-jobs
resources:
  - namespace.yaml
  - resource_quota.yaml
  - service_account.yaml
configMapGenerator:
  - name: trivy
    literals:
      - OFFLINE_SCAN=true
      - SERVER=http://trivy.image-scanner.svc.cluster.local
      - TIMEOUT=30m
generatorOptions:
  disableNameSuffixHash: true
