---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
# FIXME: Somehow sessionAffinity does not work when running e2e tests in some environments
patches:
  # Disable trivy server sessionAffinity; not really needed when running a single replica
  - target:
      kind: Service
      name: trivy
    patch: |-
      - op: remove
        path: /spec/sessionAffinity
